(define-library (kons actions test)
  (export cmd-test)
  (import (scheme base)
    (scheme file)
    (scheme process-context)
    (scheme write)
    (kons util)
    (kons implementation)
    (kons manifest)
    (kons features)
    (kons lock)
    (kons runner)
    (kons ui)
    (kons options)
    (kons actions activation)
    (kons actions targets))

  (begin
    (define (cmd-test cmd)
      (let* ((manifest (parse-manifest (command-manifest-path cmd)))
             (features (active-features manifest cmd)))
        (ensure-supported-active-features manifest features cmd)
        (cond
          ((command-flag? cmd "list")
            (writeln (test-targets-form manifest cmd features)))
          ((command-flag? cmd "plan")
            (let* ((files (selected-test-files manifest cmd))
                   (scheme (adapter-scheme manifest (command-selected-scheme cmd)))
                   (srcs (activation-source-roots-with-build manifest #t features cmd))
                   (command (and (pair? files)
                             (adapter-command-for-cmd manifest cmd scheme srcs (car files) '()))))
              (writeln
                `(test-plan
                  (root ,(package-name manifest))
                  (features ,@features)
                  (profile ,(command-selected-profile cmd))
                  (includes-dev-dependencies #t)
                  (tests ,@files)
                  (source-roots ,@srcs)
                  (load-paths ,@srcs)
                  (command ,command)
                  (dependencies ,@(all-dependencies-for manifest #t features cmd))))))
          (else
            (ensure-dev-activation-ready! manifest features cmd)
            (ensure-implementation-compiled! manifest features cmd)
            (let* ((files (selected-test-files manifest cmd)))
              (if (null? files)
                (log-info "no tests found")
                (for-each
                  (lambda (file)
                    (ui-display-status "Running" 'cyan
                      (string-append "test " file))
                    (run-activated-script manifest cmd file #t '()))
                  files)))))))))
